#!/bin/tcsh
#PBS -N imagery_test
#PBS -l walltime=72:00:00
#PBS -l nodes=1:ppn=48
#PBS -j oe

source "/usr/local/anaconda3-2021.05/etc/profile.d/conda.csh"
module load use.own anaconda3/2021.05 meltemi/openmpi-3.1.4 gcc/9.3.0
unsetenv PYTHONPATH
conda activate mpitorch

cd mpi_pytorch

python b.py
