#!/bin/tcsh
#PBS -l nodes=4:vortex:ppn=12
#PBS -N head_node
#PBS -l walltime=01:00:00
#PBS -j oe


source "/usr/local/anaconda3-2021.05/etc/profile.d/conda.csh"
module load anaconda3/2021.05 openmpi/3.1.4/gcc-9.3.0
unsetenv PYTHONPATH
conda activate mpitorch

cd mpi_pytorch


mpirun python run.py


module load anaconda3/2021.05 meltemi/openmpi-3.1.4 gcc/9.3.0
